[font]
size = 18.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
opacity = 0.9
option_as_alt = "OnlyLeft"

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]
